{
 "title": "API Latency",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  2xx Response ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=~\"2..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  3xx Response ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=~\"3..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  4xx Response ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=~\"4..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  5xx Response ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{status_code=~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}