apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-config
data:
{{- range $name, $value := .Values.configs }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
