{{- if .Values.secrets }}
{{- $values := .Values }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" . }}-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: {{ .Values.secrets.secretStore }} 
    kind: ClusterSecretStore
  target:
    name: {{ include "app.name" . }}-secret
  data:
  {{- range $v := .Values.secrets.data }}
  - secretKey: {{ $v.name }}
    remoteRef:
      key: {{ $values.secrets.secretPath }}
      property: {{ $v.property }}
  {{- end }}
{{- end }}
