apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  - name: https
    port: 443
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
