name: Build, and Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Publish, and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD       

      - name: Server - Build, tag, and push image to Dockerhub
        id: server_filter
        run: |
          # Build a docker image
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          latest_image="$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$git_hash"
          cd app/ && docker build -t $latest_image .

          echo "Pushing image to dockerhub..."
          docker push $latest_image
        env:
          DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
          DOCKER_REPOSITORY: nodejs-demo
